USE M_PEOPLES
GO

CREATE PROC SP_SelectAll
AS
	BEGIN
		SELECT ID_FUNCIONARIO				AS CÓDIGO
		,CONCAT(NOME, + ' ', + SOBRENOME)	AS 'NOME COMPLETO'
		FROM TBL_FUNCIONARIOS
	END
GO

CREATE PROC SP_SelectByID @IdFuncionario INT
AS
	BEGIN
		SELECT CONCAT(NOME, + ' ', + SOBRENOME) AS 'NOME COMPLETO'
		FROM TBL_FUNCIONARIOS
		WHERE ID_FUNCIONARIO = @IdFuncionario
	END
GO

CREATE PROC SP_Insert @Nome VARCHAR(255), @Sobrenome VARCHAR(255)
AS
	BEGIN
		INSERT INTO TBL_FUNCIONARIOS(NOME, SOBRENOME)
		VALUES (@Nome, @Sobrenome)
	END
GO

CREATE PROC SP_Delete @Id INT
AS
	BEGIN
		DELETE FROM TBL_FUNCIONARIOS
		WHERE ID_FUNCIONARIO = @Id
	END
GO

EXEC SP_SelectAll
EXEC SP_SelectByID 2
EXEC SP_Insert 'Guilherme','Volpe'
EXEC SP_Delete 3